### ISSUE TITLE
Provide Helm chart to simplify installation

### ISSUE THREAD

**Issue by tomkerkhove** [awslabs/karpenter#152]
Provide Helm chart to simplify installation and not have to run any scripts.

**Comment by ellistarn** [comment]
Thanks for the issue!

Does this meet your needs in the short term?

https://github.com/awslabs/karpenter#installation
```
CLOUD_PROVIDER=aws
VERSION=v0.1.0
kubectl apply -f https://raw.githubusercontent.com/awslabs/karpenter/master/releases/${CLOUD_PROVIDER}/${VERSION}.yaml
```

**Comment by tomkerkhove** [comment]
Yes it does but having a `helm install karpenter` would be even better for CI/CD.

**Comment by ellistarn** [comment]
Loud and clear :)

**Comment by ellistarn** [comment]
Should be taken care of here:
https://github.com/awslabs/karpenter/pull/175
```
helm repo add karpenter https://awslabs.github.io/karpenter/charts
helm install karpenter karpenter/karpenter
```

**Comment by tomkerkhove** [comment]
Great, thanks!
