### ISSUE TITLE
Move Karpenter control plane image to public repository

### ISSUE THREAD

**Issue by cameronsenese** [awslabs/karpenter#173]
Karpenter control plane image (currently at v0.1.0) is made available via private container repository.
To simplify access, and serve a broader set of deployment scenarios: suggest moving to an ECS public registry.

Current image location:
`197575167141.dkr.ecr.us-west-2.amazonaws.com/karpenter:v0.1.0@sha256:b80ac089c17f15ac37c5f62780c9761e5725463f8a801cb4a4fb69af75c17949`

Referenced by:
`https://github.com/awslabs/karpenter/blob/main/releases/aws/v0.1.0.yaml`

**Comment by ellistarn** [comment]
Thank you! Resolved by #171 
https://github.com/awslabs/karpenter/blob/main/releases/aws/v0.1.0.yaml#L925
