### ISSUE TITLE
Find a good Working Group meeting time

### ISSUE THREAD

**Issue by ellistarn** [awslabs/karpenter#179]
Let's find a time that works for both US-West and EU-East timezones. The working group is currently uncomfortably late for our EU-East friends at Friday 6pm.
https://github.com/awslabs/karpenter/tree/main/docs/working-group

[![](https://api.gh-polls.com/poll/01ERQM6RAQT8BS3G02Z248JC9K/Tuesday%209am%20PST)](https://api.gh-polls.com/poll/01ERQM6RAQT8BS3G02Z248JC9K/Tuesday%209am%20PST/vote)
[![](https://api.gh-polls.com/poll/01ERQM6RAQT8BS3G02Z248JC9K/Tuesday%2010am%20PST)](https://api.gh-polls.com/poll/01ERQM6RAQT8BS3G02Z248JC9K/Tuesday%2010am%20PST/vote)
[![](https://api.gh-polls.com/poll/01ERQM6RAQT8BS3G02Z248JC9K/Thursday%209am%20PST)](https://api.gh-polls.com/poll/01ERQM6RAQT8BS3G02Z248JC9K/Thursday%209am%20PST/vote)
[![](https://api.gh-polls.com/poll/01ERQM6RAQT8BS3G02Z248JC9K/Thursday%2010am%20PST)](https://api.gh-polls.com/poll/01ERQM6RAQT8BS3G02Z248JC9K/Thursday%2010am%20PST/vote)

**Comment by tomkerkhove** [comment]
Voted for 9 AM PST as that is more ideal for people in EU

**Comment by gjtempleton** [comment]
Thanks for the options, appreciate it!

**Comment by ellistarn** [comment]
9am tuesday it is. We'll start this up in the new year.
