### ISSUE TITLE
failed retrieving metric, request failed for query karpenter_reserved_capacity_cpu_utilization{name=\"demo\"}, Post \"http://prometheus-operated:9090/api/v1/query\": dial tcp: lookup prometheus-operated on 10.100.0.10:53: no such host

### ISSUE THREAD

**Issue by Balukeethu** [awslabs/karpenter#186]
i have not configured prometheus yet. even though its redirecting to the below specified URL and its failing to collect the metrices. Can you please tell me where this configuration is made ? and how do i change it?

failed retrieving metric, request failed for query karpenter_reserved_capacity_cpu_utilization{name=\"demo\"}, Post \"http://prometheus-operated:9090/api/v1/query\": dial tcp: lookup prometheus-operated on 10.100.0.10:53: no such host

**Comment by ellistarn** [comment]
Hey @Balukeethu 👋 . It looks like you may have solved your own problem. We have an install script that includes prometheus https://github.com/awslabs/karpenter#quick-install---controller--dependencies. 

If you want to configure a custom prometheus endpoint, simply update this https://github.com/awslabs/karpenter/blob/main/cmd/controller/main.go#L50
