### ISSUE TITLE
[Provisioning] AMI Support

### ISSUE THREAD

**Issue by ellistarn** [awslabs/karpenter#229]
Currently AMI is hardcoded. Use SSM to detect the best EKSOptimizedAMI for kubernetes version.

1. Query: kubectl get --raw /version
2. Pass k8s version to SSM for EKSOptimized AMI

Example: https://github.com/aws/aws-cdk/blob/v1.88.0/packages/@aws-cdk/aws-eks-legacy/lib/cluster.ts#L836

**Comment by prateekgogia** [comment]
Merged by https://github.com/awslabs/karpenter/pull/242
