### ISSUE TITLE
Support aarch64 EKS amis

### ISSUE THREAD

**Issue by JacobGabrielson** [awslabs/karpenter#260]
Presently the AWS provider only supports `x86_64` worker nodes - this issue is to add `aarch64` support to the Provisioner.

**Comment by ellistarn** [comment]
What's in scope for this? Launching arm nodes? Running Karpenter as ARM? Helm charts?

**Comment by JacobGabrielson** [comment]
> What's in scope for this? Launching arm nodes? Running Karpenter as ARM? Helm charts?

Updated

**Comment by JacobGabrielson** [comment]
fixed by https://github.com/awslabs/karpenter/pull/265
