### ISSUE TITLE
[Provisioning] Implement Pod Topology Spread

### ISSUE THREAD

**Issue by ellistarn** [awslabs/karpenter#268]
Support node affinity in constraint groups.

**Comment by Funcan** [comment]
This is a very interesting feature from Groupon's point of view - we're just starting to properly test topology spread constraints to solve some very real availability constraints we're seeing, and we hope to switch to karpenter as it becomes more mature to solve other issues we're having with the default cluster autoscaler

**Comment by ellistarn** [comment]
Great to hear @Funcan. We'll update here once we have something more concrete for Topology Spread.
