### ISSUE TITLE
Reallocator test suites

### ISSUE THREAD

**Issue by njtran** [awslabs/karpenter#277]
Reallocator needs some test suites

**Comment by njtran** [comment]
Implemented some base tests. 
https://github.com/awslabs/karpenter/commit/cd774f5cfa4f74d3f6c7b5bcbf4820d4870c0325 

Need more tests, but blocked on more robust implementation of the reallocation controller. Without that robust implementation, the GHA tests run into race-conditions.

**Comment by bwagner5** [comment]
we have tests now.
