### ISSUE TITLE
Remove IAM API Runtime Dependency

### ISSUE THREAD

**Issue by bwagner5** [awslabs/karpenter#388]
In the AWS CloudProvider there is an InstanceProfile provider that retrieves the IAM role attached to the Karpenter Node Instance Profile. The Karpenter Node Instance Profile is a static name, but the IAM Role attached to the profile could be different.  The role is needed to update a config map for the Node to have IAM Roles For Service Accounts (IRSA). Applicable code: https://github.com/awslabs/karpenter/blob/9e4f4676816d4f4494f5b3e988fb6c2b04d77ab5/pkg/cloudprovider/aws/instanceprofile.go#L58-L74

Some users need to operate Karpenter in a no-Internet environment and there is no IAM VPC Endpoint.

The instance profile is already being added to the LaunchTemplate when launching the instance so I believe that adding each node IAM role mapping to the auth config map is unnecessary. If I'm no mistaken, we can just remove all of the InstanceProfile provider. https://github.com/awslabs/karpenter/blob/bf633b732db4eb06d8f3a67866a8e0781c4201f4/pkg/cloudprovider/aws/launchtemplate.go#L134

**Comment by ellistarn** [comment]
Related to https://github.com/awslabs/karpenter/issues/257
