### ISSUE TITLE
Graceful node termination (cordon/drain)

### ISSUE THREAD

**Issue by akestner** [awslabs/karpenter#452]
_(Creating issues to track `v0.3` roadmap items in #435, will update this description with more details in the coming days)_

**Comment by mattparkes** [comment]
Just an FYI, this is becoming built-in: https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/

**Comment by njtran** [comment]
Hey Matt. Thanks for bringing this up! We'll definitely be utilizing this in the future to reduce the work that Karpenter has to do for graceful node shutdown. As the Kubernetes [site](https://kubernetes.io/docs/concepts/architecture/nodes/#graceful-node-shutdown) says that it is a 1.21 beta feature right now and we haven't verified 1.21 for Karpenter yet, we can't use this. 

In the meantime, we'll be using the process referenced in the [termination design doc](https://github.com/awslabs/karpenter/blob/main/docs/designs/termination.md). In the future we should re-evaluate and deduplicate the work we do here.

**Comment by ellistarn** [comment]
#534
