### ISSUE TITLE
Batch Pod Creations on Watch Events

### ISSUE THREAD

**Issue by bwagner5** [awslabs/karpenter#467]
Currently, the controller naively checks for pod creations within a 5 second interval. This results in suboptimal provisioned nodes since pod creation events often happen at the same time (ie. a Deployment scale up). A better approach would be to watch for pod creation events and then wait some period of time with the intent of giving the API server some more time to create its backlog of pods.  

This will artificially add a few seconds to node provisioning based on the first pod that is created but the benefit of provisioning larger  (less overhead) and better packed nodes outweighs this cost. The interval wasn't necessarily better in regards to node provisioning time anyways, since a new pod could have come in right after the check ran and so node provisioning would have to wait for the 5 seconds anyways.

**Comment by ellistarn** [comment]
Let's make this interval configurable, as well. Maybe default = 5?
