### ISSUE TITLE
Scheduling: Inter-Pod Affinity

### ISSUE THREAD

**Issue by akestner** [awslabs/karpenter#483]
From [Kubernetes docs](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity):

>Inter-pod affinity and anti-affinity allow you to constrain which nodes your pod is eligible to be scheduled based on labels on pods that are already running on the node rather than based on labels on nodes. The rules are of the form "this pod should (or, in the case of anti-affinity, should not) run in an X if that X is already running one or more pods that meet rule Y". Y is expressed as a LabelSelector with an optional associated list of namespaces; unlike nodes, because pods are namespaced (and therefore the labels on pods are implicitly namespaced), a label selector over pod labels must specify which namespaces the selector should apply to. Conceptually X is a topology domain like node, rack, cloud provider zone, cloud provider region, etc. You express it using a topologyKey which is the key for the node label that the system uses to denote such a topology domain; for example, see the label keys listed above in the section Interlude: [built-in node labels](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#built-in-node-labels).

**Comment by ellistarn** [comment]
Some preliminary thoughts on this. 

I think we're necessarily going to be forced to support a known set of topology domains. This is similar to the well known NodeSelectors mechanism we use, and we might start with the cloud agnostic and documented domains:`topology.k8s.io/zone` and `topology.k8s.io/hostname`. It's likely that over time, we will need to be extensible to additional topology domains, perhaps on both a generic and cloud provider basis.

These two examples demonstrate the emergent complexity in topology. For example, zones are of a finite set ~= 3, where hostname is an infinite set of existing nodes + potential nodes. Balancing pods across a finite set is straight forward, but what do you do when "balancing" across an infinite set. We could simply launch 1 pod per node, but that may violate the maxSkew of pods that are already scheduled onto existing nodes. It's also possible that the current spread could be 3 pods per existing node, yet the upcoming nodes might only be able to have a single pod, which would violate max skew.

**Comment by bwagner5** [comment]
Sticking to pod topology rather than inter-pod affinity due to recommendation from SIG scalability.
