### ISSUE TITLE
[Request]: Provisioners should not be namespaced

### ISSUE THREAD

**Issue by ellistarn** [awslabs/karpenter#496]
**Tell us about your request**
It's awkward that provisioners are a namespaced resource that launch unnamespaced resources (nodes). Additionally -- it may make sense in the future to have a concept of a default provisioner, and this model does not map well if provisioners are namespaced (since pods and nodes transcend namespaces). 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
whoops, I didn't see this already exists. More details are in the other issue though, so closing in favor of #510.
