### ISSUE TITLE
move markdown files to /docs

### ISSUE THREAD

**Issue by geoffcline** [awslabs/karpenter#537]
move markdown files to /docs and delete /website

update netlify and makefile as required

**Comment by ellistarn** [comment]
I'm not sure I agree with this. I think keeping the website in the website folder makes sense. I think it makes sense to keep technical things (like design docs) in /docs.

**Comment by geoffcline** [comment]
could we do /design-docs and /website?

I heard today that /docs and /website was confusing.

**Comment by ellistarn** [comment]
Where did that confusion come from? It's fairly standard from other projects to have technical docs in a `/docs` folder. 
https://github.com/knative/serving
https://github.com/tektoncd/pipeline

It's common to have the website as a second repo, but we don't have our own organization (yet).

**Comment by geoffcline** [comment]
I think if we have a website that's 90% docs, and that content doesn't live in the `/docs` folder, that will be confusing. 

It was @rothgar who pinged me asking about why /docs and /website.

**Comment by geoffcline** [comment]
I've decided i'm fine with the existing structure.
