### ISSUE TITLE
Helm installation command needs to be updated with --create-namespace

### ISSUE THREAD

**Issue by abeer91** [awslabs/karpenter#545]
On page - https://karpenter.sh/docs/getting-started/ 

## Expected Behavior
Command to install Karpenter using helm should've worked.

## Actual Behavior

Got Error: `Error: create: failed to create: namespaces "karpenter" not found`

## Steps to Reproduce the Problem
Command is: `helm upgrade --install karpenter karpenter/karpenter \
  --namespace karpenter --set serviceAccount.create=false`

On using this command I get
```
(cli-ve) ➜  ~ helm upgrade --install karpenter karpenter/karpenter \                                           [21/07/23| 3:16PM]
  --namespace karpenter --set serviceAccount.create=false
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/abeers/.kubeconfig/config-onetwozero
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/abeers/.kubeconfig/config-onetwozero
WARNING: "kubernetes-charts.storage.googleapis.com" is deprecated for "stable" and will be deleted Nov. 13, 2020.
WARNING: You should switch to "https://charts.helm.sh/stable" via:
WARNING: helm repo add "stable" "https://charts.helm.sh/stable" --force-update
Release "karpenter" does not exist. Installing it now.
Error: create: failed to create: namespaces "karpenter" not found
```

I needed to add the argument `--create-namespace` to get it work.

## Version

**Karpenter**: v0.0.0

**Kubernetes**: v1.0.0

**Comment by ellistarn** [comment]
https://github.com/awslabs/karpenter/pull/546
