### ISSUE TITLE
clarify support for topologySpreadConstraints

### ISSUE THREAD

**Issue by geoffcline** [awslabs/karpenter#548]
After reading

> Does Karpenter support topology spread constraints?
> Yes. Provisioners respect pod.spec.topologySpreadConstraints. Allocating pods with these constraints may yield highly fragmented nodes, due to their strict nature and complexity of “online binpacking” algorithms.

I assumed karpenter would create nodes and then schedule them but it looks like until nodes exist that will fit that criteria no nodes will be created

**Comment by akestner** [comment]
What's the status here? Are there other inaccuracies in the docs that would confuse users?

**Comment by geoffcline** [comment]
The status here is that we don't support topology spread constraints, so my question about implications is moot.
