### ISSUE TITLE
Analytics Governance?

### ISSUE THREAD

**Issue by geoffcline** [awslabs/karpenter#559]
The admin for the google analytics account is my `gcline@amazon.com` google account. 

Consider:
1. documenting this, and allowing community access
2. moving the google analytics account under a google organization in the future

**Comment by ellistarn** [comment]
Is it possible to have a karpenter owned google org?

**Comment by geoffcline** [comment]
Yes, but I think the value lies in having it integrated with a google directory service (gcp cloud identity or google workspace directory)

**Comment by akestner** [comment]
I don't see anything Google Analytics related in the website config. Last I saw, it was the same values as the Docsy example site. Where is this config?

**Comment by geoffcline** [comment]
> I don't see anything Google Analytics related in the website config. Last I saw, it was the same values as the Docsy example site, so I removed it. Where is this config?

https://github.com/awslabs/karpenter/blob/c5c2c4f31d74493beb2f9d0f9660f0fddfb489b0/website/config.toml#L15

**Comment by geoffcline** [comment]
resolved as we are using netlify analytics, which is cookieless.
