### ISSUE TITLE
Karpenter Provisioned EC2 Node Fails to Join Cluster

### ISSUE THREAD

**Issue by akestner** [awslabs/karpenter#601]
## Version

**Karpenter**: v0.3.0

**Kubernetes**: v1.20

## Expected Behavior
New nodes spun up by Karpenter will join the cluster successfully and start receiving workloads.

## Actual Behavior
Nodes (EC2 instances) provisioned by Karpenter never leave `NotReady` status.

## Steps to Reproduce the Problem
1. Create a cluster using the following `eksctl` cluster config:
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster-name
  region: us-west-2
  version: "1.20"
managedNodeGroups:
  - instanceType: m5.xlarge
    name: cluster-name-nodegroup
    desiredCapacity: 2
    minSize: 2
    maxSize: 10
    ssh:
      enableSsm: true
secretsEncryption:
  keyARN: <ARN>
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: karpenter
        namespace: karpenter
      attachPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              # Write Operations
              - "ec2:CreateLaunchTemplate"
              - "ec2:CreateFleet"
              - "ec2:RunInstances"
              - "ec2:CreateTags"
              - "iam:PassRole"
              - "ec2:TerminateInstances"
              # Read Operations
              - "ec2:DescribeLaunchTemplates"
              - "ec2:DescribeInstances"
              - "ec2:DescribeSecurityGroups"
              - "ec2:DescribeSubnets"
              - "ec2:DescribeInstanceTypes"
              - "ec2:DescribeInstanceTypeOfferings"
              - "ec2:DescribeAvailabilityZones"
              - "ssm:GetParameter"
addons:
- name: vpc-cni
  version: 1.9.0
```
2. Follow Getting Started Guide from ["Tag Subnets"](https://karpenter.sh/docs/getting-started/#tag-subnets).
3. Scale the `inflate` deployment up enough to require new nodes.
4. Observe that some `inflate` pods are not scheduled and that the new nodes don't join the cluster.

## Additional Info
Here's a dump of `kubectl get nodes <node-name> -o yaml` from one of the nodes that failed to join:
```yaml
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
  creationTimestamp: "2021-08-10T01:26:55Z"
  finalizers:
  - karpenter.sh/termination
  labels:
    karpenter.sh/provisioner-name: default
  name: ip-192-168-xxx-xxx.us-west-2.compute.internal
  resourceVersion: "20112"
  uid: xxxxxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx
spec:
  providerID: aws:///us-west-2a/i-xxxxxxxxxxxxx
  taints:
  - effect: NoSchedule
    key: karpenter.sh/not-ready
  - effect: NoSchedule
    key: node.kubernetes.io/unreachable
    timeAdded: "2021-08-10T01:27:59Z"
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    timeAdded: "2021-08-10T01:27:59Z"
status:
  allocatable:
    cpu: "8"
    memory: 30310Mi
    pods: "58"
  conditions:
  - lastHeartbeatTime: "2021-08-10T01:26:55Z"
    lastTransitionTime: "2021-08-10T01:27:59Z"
    message: Kubelet never posted node status.
    reason: NodeStatusNeverUpdated
    status: Unknown
    type: Ready
  - lastHeartbeatTime: "2021-08-10T01:26:55Z"
    lastTransitionTime: "2021-08-10T01:27:59Z"
    message: Kubelet never posted node status.
    reason: NodeStatusNeverUpdated
    status: Unknown
    type: MemoryPressure
  - lastHeartbeatTime: "2021-08-10T01:26:55Z"
    lastTransitionTime: "2021-08-10T01:27:59Z"
    message: Kubelet never posted node status.
    reason: NodeStatusNeverUpdated
    status: Unknown
    type: DiskPressure
  - lastHeartbeatTime: "2021-08-10T01:26:55Z"
    lastTransitionTime: "2021-08-10T01:27:59Z"
    message: Kubelet never posted node status.
    reason: NodeStatusNeverUpdated
    status: Unknown
    type: PIDPressure
  daemonEndpoints:
    kubeletEndpoint:
      Port: 0
  nodeInfo:
    architecture: x86_64
    bootID: ""
    containerRuntimeVersion: ""
    kernelVersion: ""
    kubeProxyVersion: ""
    kubeletVersion: ""
    machineID: ""
    operatingSystem: linux
    osImage: ""
    systemUUID: ""
```

Provisioner via `kubectl get Provisioner -o yaml`

```yaml
apiVersion: v1
items:
- apiVersion: karpenter.sh/v1alpha3
  kind: Provisioner
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"karpenter.sh/v1alpha3","kind":"Provisioner","metadata":{"annotations":{},"name":"default"},"spec":{"cluster":{"endpoint":"https://xxxxxxxxxxx.xxxxxx.us-west-2.eks.amazonaws.com","name":"cluster-name"},"ttlSecondsAfterEmpty":30}}
    creationTimestamp: "2021-08-10T00:40:30Z"
    generation: 1
    name: default
    resourceVersion: "6272"
    uid: xxxxxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx
  spec:
    cluster:
      endpoint: https://xxxxxxxxxxx.xxxxxx.us-west-2.eks.amazonaws.com
      name: cluster-name
    ttlSecondsAfterEmpty: 30
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by ellistarn** [comment]
It's hard to know the connectivity problem without either debugging Bottlerocket instances directly. I have a few guesses.

## Symptom
I see the error: `Kubelet never posted node status`. Are the instances online in your account? My guess is yes, because if they're not, the cluster's cloud controller manager would have deleted the node objects. This makes me think that the auth isn't wired up correctly.

## Verify Cluster Name + Endpoint Match
Is there any chance that your environment variables got tangled somehow, and this isn't lining up correctly? 
```
      endpoint: https://xxxxxxxxxxx.xxxxxx.us-west-2.eks.amazonaws.com
      name: cluster-name
```

## Double check your AWS Auth Configmap
```
kubectl get configmaps -n kube-system aws-auth -oyaml
```
Make sure this matches the role you created

**Comment by rr-paras-patel** [comment]
i have similar situation. 100s of nodes are in "notready" state. and i am not able to delete those node via `kubectl delete node`. as last step i had to go to ec2 console and deleted node. but not able to delete it from cluster.

**Comment by abatilo** [comment]
I'm having this same problem on an EKS cluster with v1.21 and Karpenter v0.5.1. Nodes keep getting provisioned and none of them ever join the cluster.

```
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::ID:role/usw2-eks-a2021110619174516420000000b"
      "username": "system:node:{{EC2PrivateDNSName}}"
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::ID:role/karpenter-usw2-eks-a"
      "username": "system:node:{{EC2PrivateDNSName}}"
```

My AWS config map looks identical between the managed node group that I have and the IAM node role for the Karpenter provisioned nodes.

Security groups match. Everything matches except I never see leases provisioned for any of these nodes when I do a `kubectl get leases -A`.

I've verified that the cluster-name and the endpoint are correct in the helm chart for the controller.

What else can I check @ellistarn? I followed all of the instructions for the getting started and the nodes just flat out won't join.

**Comment by danerkninja** [comment]
did anyone ever get this to work?

**Comment by ellistarn** [comment]
This issue was on a very old version of karpenter and hadn't had any responses. Check out: https://github.com/aws/karpenter/blob/main/TROUBLESHOOTING.md#node-notready. Feel free to reach out on slack if you need some help debugging.

**Comment by danivendetta** [comment]
> This issue was on a very old version of karpenter and hadn't had any responses. Check out: https://github.com/aws/karpenter/blob/main/TROUBLESHOOTING.md#node-notready. Feel free to reach out on slack if you need some help debugging.

The link is Broken.

I'm getting the same error.

**Comment by samchan0221** [comment]
> > > This issue was on a very old version of karpenter and hadn't had any responses. Check out: https://github.com/aws/karpenter/blob/main/TROUBLESHOOTING.md#node-notready. Feel free to reach out on slack if you need some help debugging.
> > 
> > 
> > The link is Broken.
> > I'm getting the same error.
> 
> hopefully, they can put it back up, that article solved my problem
> 
> edit: looks like they moved it here https://karpenter.sh/v0.7.1/troubleshooting/

The link is still borken, can you link the commit where the documentation was there?

**Comment by FernandoMiguel** [comment]
@samchan0221 this https://karpenter.sh/v0.27.3/troubleshooting/ ?
just go to the homepage, click docs, then troubleshooting

**Comment by aponyrko** [comment]
I ran into a similar issue and it ended up being related to SecurityGroups. Specifically, the EKS API SecurityGroup that EKS otherwise adds to NodeGroup EC2 instances that Karpenter doesn't know to add to NodePool EC2 instances in the absence of the discovery tag.

Instructions for locating the SecurityGroup: https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html
