### ISSUE TITLE
Using a library against the terms of its license

### ISSUE THREAD

**Issue by Catbuttes** [awslabs/karpenter#608]
Karpenter currently has a dependancy on [bouk/monkey](https://github.com/bouk/monkey) in /pkg/controllers/node/suite_test.go, which has the following license

```
Copyright Bouke van der Bijl
I do not give anyone permissions to use this tool for any purpose. Don't use it.
I’m not interested in changing this license. Please don’t ask.
```

**Comment by ellistarn** [comment]
Wow nice catch! https://github.com/awslabs/karpenter/pull/609. We need to add some automation here.

**Comment by ellistarn** [comment]
https://github.com/awslabs/karpenter/pull/609

**Comment by ellistarn** [comment]
https://github.com/awslabs/karpenter/pull/611
