### ISSUE TITLE
Spot as Default Capacity Type 

### ISSUE THREAD

**Issue by rr-paras-patel** [awslabs/karpenter#613]
We should start with default capacity type as spot instances. 
I recently encountered issue due to some reason karpenter was keep launching nodes and node were in "not ready" state.
and previously launched nodes were not being terminated by karpenter result into 500 or More On Demand node was launched in few hours and it was costly mistake for someone who is trying to contribute in open source project. 
I am happy to raise PR for this change. 
Current Hidden documentation about this default is here : https://karpenter.sh/docs/provisioner-crd/

**Comment by ellistarn** [comment]
Hey @rr-paras-patel this is a known bug right now. We thought that the [liveness controller](https://github.com/awslabs/karpenter/blob/main/pkg/controllers/node/liveness.go#L38) should take care of it, but it looks like there's a bug for some kubernetes version. The behavior *should* be to terminate nodes when they cannot connect for 5 minutes. In this case, Karpenter will attempt to provision nodes in response to pending pods, and the pods have a toleration for 5 minutes of a node not being ready, so you'll see a new node every 5 minutes or so. I'm going to look into a fix for this. 

I think it's a great idea to put `node.k8s.aws/capacity-type: "spot"` into the getting started guide. If you're suggesting that we should launch spot by default (without labels), I think this is a longer discussion. Feel free to reach out on the Kubernetes slack if you want to chat synchronously. I can also help debug this NotReady issue.
