### ISSUE TITLE
Issue withe the Tag subnets part

### ISSUE THREAD

**Issue by laghao** [awslabs/karpenter#630]
Under the documentation Getting started with Karpenter section [tag-subnets](https://karpenter.sh/docs/getting-started/#tag-subnets) the tag value is missing:

```
aws ec2 create-tags \
    --resources $(echo $SUBNET_IDS | tr ',' '\n') \
    --tags Key="kubernetes.io/cluster/${CLUSTER_NAME}",Value=
```

**Comment by ellistarn** [comment]
This tag is intentionally an empty string (IIUC). I suppose it could be set to "owned". Is this causing errors?

**Comment by laghao** [comment]
It's indeed working, just tested it now without tag value, it was misleading as the section describes "Retreive the subnet IDs and tag them with the cluster name." so I added value=${CLUSTER_NAME}

**Comment by ellistarn** [comment]
Anything left here, or can we close?
