### ISSUE TITLE
[HorizontalAutoscaler] HA ScaleTargetRef broken if replicas is not defined in SNG

### ISSUE THREAD

**Issue by ellistarn** [awslabs/karpenter#64]
{
      "lastTransitionTime": "2020-11-03T18:29:50Z",
      "message": "getting scale target for {ScalableNodeGroup demo autoscaling.karpenter.sh/v1alpha1}, Internal error occurred: the spec replicas field \".spec.replicas\" does not exist",
      "status": "False",
      "type": "Active"
    },

**Comment by JacobGabrielson** [comment]
I *think* the error is being generated from here, although not 100% sure ...

https://github.com/kubernetes/client-go/blob/master/rest/request.go#L1031
