### ISSUE TITLE
api spec is hard to read

### ISSUE THREAD

**Issue by trondhindenes** [awslabs/karpenter#645]
**Tell us about your request**
trying to add labels and taints

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
When looking at the api reference (https://karpenter.sh/docs/reference/#karpenter.sh/v1alpha3.ProvisionerSpec), it looks like `Constraints` is a field inside `spec`. However, looking at the installed CRD, constraint fields such as `labels` and `taints` should be specified directly on the `Provisioner.spec`. This is confusing. Docs should provide an easy-to-read overview of the spec simiular to the official Kubernetes docs

**Are you currently working around this issue?**
Looked at the CRD definition directly

**Additional context**

**Attachments**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Hey @trondhindenes, this is an unfortunately side effect of our docs generator, which doesn't support embedded types well. We hope to make improvements to our docs so we can avoid challenges with the autogenerated docs.

**Comment by bwagner5** [comment]
solved in v1alpha4
