### ISSUE TITLE
Provisioner "default" not found

### ISSUE THREAD

**Issue by trondhindenes** [awslabs/karpenter#656]
## Version
**Karpenter**: v0.3.2
**Kubernetes**: v1.21.0

## Expected Behavior
Karpenter should search in all namespaces for the "default" provisioner.

## Actual Behavior
After placing a provisioner called "default" in the "karpenter" namespace, I'm still seeing:
`Provisioner "default" not found` in the logs. It looks like only the "default" namespace is considered. We try and avoid putting anything at all in the default namespace

## Steps to Reproduce the Problem
place a "default" provisioner in any other namespace (such as a namespace called "karpenter")

**Comment by ellistarn** [comment]
Karpenter provisioners are a global resource like Kubernetes nodes. Provisioners cannot be applied into namespaces. Hope this clears things up.

**Comment by ellistarn** [comment]
> After placing a provisioner called "default" in the "karpenter" namespace, I'm still seeing:
Provisioner "default" not found in the logs. 
This is strange to me. I wonder if you somehow have multiple karpenter CRDs installed (perhaps from an older version)?

**Comment by trondhindenes** [comment]
Sorry for jumping to conclusions. I saw in the log that the provisioner default wasn't found, but discovered later that Kareptner does very little "success" logging, so the error was much more transient thant what the logs led me to believe.

**Comment by ellistarn** [comment]
This is great feedback. Maybe we can log something like "waiting for pending pods" as the last step of the reconcile loop. I think we should also log of we see zero pending pods.
