### ISSUE TITLE
API Improvements Uber Issue

### ISSUE THREAD

**Issue by ellistarn** [awslabs/karpenter#661]
**Tell us about your request**
API Changes

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
https://github.com/awslabs/karpenter/issues/632
https://github.com/awslabs/karpenter/issues/642
https://github.com/awslabs/karpenter/issues/646

**Are you currently working around this issue?**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
solved in v1alpha4
