### ISSUE TITLE
New EC2 Instance Types can't initialize

### ISSUE THREAD

**Issue by njtran** [awslabs/karpenter#673]
## Version

**Karpenter**: v0.3.2

**Kubernetes**: v1.20.0

## Behavior
Currently when scaling up a large amount of pods, Karpenter can select the new m6i.32xlarge instance types for new capacity. These instances along with others currently are unable to initialize the CNI Plugin, resulting in the nodes never being able to join the cluster, which will cause a lot of churn in the cluster.

## Issue tracking
Currently vpc-cni uses a [hardcoded list](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/awsutils/vpc_ip_resource_limit.go) of known instance types.  The current instance type is [fetched from IMDS at startup](https://github.com/aws/amazon-vpc-cni-k8s/blob/2e7d7c824ef38daa65029865f02dbc12e50ab807/pkg/awsutils/awsutils.go#L419), and looked up in this list to find the [secondary IP max limit](https://github.com/aws/amazon-vpc-cni-k8s/blob/2e7d7c824ef38daa65029865f02dbc12e50ab807/pkg/awsutils/awsutils.go#L1251), the [ENI max limit](https://github.com/aws/amazon-vpc-cni-k8s/blob/2e7d7c824ef38daa65029865f02dbc12e50ab807/pkg/awsutils/awsutils.go#L1262), and the [hypervisor type](https://github.com/aws/amazon-vpc-cni-k8s/blob/2e7d7c824ef38daa65029865f02dbc12e50ab807/pkg/awsutils/awsutils.go#L1291) (used to give early errors for unsupported feature combinations).
Of those 3 cases, the ENI max limit and hypervisor type lookups will return an error if the instance type is not in the hardcoded list.  The ENI max limit will fallback to calling DescribeInstanceTypes and add the result to the hardcoded list at runtime.
Unfortunately the recently added (vpc-cni 1.9) PD code added an extra [check for hypervisor family](https://github.com/aws/amazon-vpc-cni-k8s/blob/2e7d7c824ef38daa65029865f02dbc12e50ab807/pkg/ipamd/ipamd.go#L323-L327) before these functions are called, resulting in some instances being unable to be used.

**Comment by bwagner5** [comment]
fixed in vpc cni v1.9.1
