### ISSUE TITLE
Twitch link in README is broken

### ISSUE THREAD

**Issue by gricey432** [awslabs/karpenter#738]
In the README there's a link to a container day talk on Twitch, however the link leads to a 404
https://github.com/awslabs/karpenter/blob/main/README.md?plain=1#L48

Is this VoD available elsewhere so the link could be updated? Or is there something an AWS Twitch account admin needs to do to make the VoD available?

**Comment by bwagner5** [comment]
Thanks for reporting this issue! The readme is updated with the correct link now :)
