### ISSUE TITLE
Automatic Node Provisioning Failed

### ISSUE THREAD

**Issue by gambit36** [awslabs/karpenter#778]
## Version

**Karpenter**: v0.4.1

**Kubernetes**: v1.20.7

## Expected Behavior

I followed https://karpenter.sh/docs/getting-started/ to deploy the environment and did not create a new node at the "Automatic Node Provisioning" step. 

## Actual Behavior

kubectl logs -f -n karpenter $(kubectl get pods -n karpenter -l karpenter=controller -o name)

2021-10-31T14:58:21.017Z        ERROR   controller.controller.Allocation        Reconciler error 
......
"ValidThreadsPerCore\":[1,2]},\"ZoneOptions\":[\"us-west-2a\",\"us-west-2c\",\"us-west-2d\",\"us-west-2b\"]}], getting launch template configs, getting launch templates, describing security groups [], InvalidParameterValue: The filter 'null' is invalid\n\tstatus code: 400, request id: 2dc6a23c-d4f6-446d-beaa-bd1529f12ed5"}

**Comment by ellistarn** [comment]
Can you check out your provisioner custom resource. If you create the provisioner before the controller is fully installed (i.e., if you don't `--wait`, it's possible to skip the defaulting webhook and have an empty `spec.provider.securityGroupSelector`. I think that's this null issue you're getting. 

This can be easily resolved by deleting and recreating your provisioner.

**Comment by gambit36** [comment]
> Can you check out your provisioner custom resource. If you create the provisioner before the controller is fully installed (i.e., if you don't `--wait`, it's possible to skip the defaulting webhook and have an empty `spec.provider.securityGroupSelector`. I think that's this null issue you're getting.
> 
> This can be easily resolved by deleting and recreating your provisioner.

Thank you very much for your reply, I think I have found the cause of the problem. Because I am running this getting started on an ec2 instance, the cluster name starts with "ec2-user". I changed the cluster name and removed the "ec2". Everything is normal.

**Comment by ellistarn** [comment]
Great! It looks like a dash is invalid for the cluster name? We should probably validate this.
