### ISSUE TITLE
Should Tag All Fleet Launches

### ISSUE THREAD

**Issue by eptiger** [awslabs/karpenter#793]
**Tell us about your request**
We should tag all the instances launched by Karpenter with a karpenter-specific tag to make it easier to find them. Right now I don't believe we tag instances launched with custom launch templates

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Identify instances launched by Karpenter

**Are you currently working around this issue?**
I'm not

**Additional context**
No

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by JacobGabrielson** [comment]
This is supposed to work already, by the way:

https://github.com/awslabs/karpenter/blob/4e0a4b441a3e42f1f1432727249d5d1e0c56eaf1/pkg/cloudprovider/aws/apis/v1alpha1/tags.go#L28

**Comment by eptiger** [comment]
Brandon had said that this didn't work for custom launch templates (which seemed logical as I only see it used in [createLaunchTemplate](https://github.com/awslabs/karpenter/blob/0aa5b8aabefefaea8588c08f76d3d2d43f7643fe/pkg/cloudprovider/aws/launchtemplate.go#L171)), but TBH I haven't had a chance to verify if that's the case or not.

**Comment by ellistarn** [comment]
Is it possible to use Fleet to tag instances outside of the user data?

**Comment by bwagner5** [comment]
Today this only works if a user has not specified a custom launch template since we implement tagging via the LaunchTemplate tag spec. It is possible to specify the tags directly via the Fleet request.
